#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# 🔥 ELECTRIC SAFAI - Data Seeding Script
#═══════════════════════════════════════════════════════════════════════════════
# Seeds dummy data into Elasticsearch for testing and development
#═══════════════════════════════════════════════════════════════════════════════

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'

# Banner
echo -e "${MAGENTA}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         ⚡ ELECTRIC SAFAI - Data Seeder ⚡                    ║"
echo "║         🌱 Populate Elasticsearch with Test Data             ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Configuration
ES_HOST="${ES_HOST:-localhost}"
ES_PORT="${ES_PORT:-9200}"
ES_URL="http://${ES_HOST}:${ES_PORT}"
INDEX_NAME="${INDEX_NAME:-electric-safai-test}"
DOC_TYPE="${DOC_TYPE:-_doc}"

echo -e "${BLUE}📋 Configuration:${NC}"
echo "   Elasticsearch: ${ES_URL}"
echo "   Index: ${INDEX_NAME}"
echo ""

# Check connection
if ! curl -s "${ES_URL}" > /dev/null 2>&1; then
    echo -e "${RED}❌ Cannot connect to Elasticsearch at ${ES_URL}${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Connected to Elasticsearch${NC}"
echo ""

# Categories for random data
CATEGORIES=("technology" "science" "business" "health" "education" "entertainment")
TAGS=("featured" "trending" "archived" "draft" "published" "urgent")

# Function to generate random data
generate_document() {
    local id=$1
    local category=${CATEGORIES[$((RANDOM % ${#CATEGORIES[@]}))]}
    local tag1=${TAGS[$((RANDOM % ${#TAGS[@]}))]}
    local tag2=${TAGS[$((RANDOM % ${#TAGS[@]}))]}
    local priority=$((RANDOM % 10 + 1))
    local timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    cat <<EOF
{
    "title": "Document ${id}: Electric Safai Test Entry",
    "description": "This is test document number ${id} generated by the Electric Safai seeding script. It contains sample data for testing Elasticsearch queries.",
    "category": "${category}",
    "tags": ["${tag1}", "${tag2}"],
    "priority": ${priority},
    "timestamp": "${timestamp}",
    "metadata": {
        "created_by": "electric-safai-seeder",
        "version": "1.0.0",
        "monk_style": "rinzai"
    }
}
EOF
}

# Function to seed documents
seed_documents() {
    local count=${1:-100}
    echo -e "${YELLOW}🌱 Seeding ${count} documents...${NC}"
    echo ""

    for i in $(seq 1 $count); do
        doc=$(generate_document $i)

        response=$(curl -s -X POST "${ES_URL}/${INDEX_NAME}/${DOC_TYPE}" \
            -H 'Content-Type: application/json' \
            -d "${doc}")

        # Progress indicator
        if (( i % 10 == 0 )); then
            echo -e "${CYAN}   📝 Seeded ${i}/${count} documents...${NC}"
        fi
    done

    echo ""
    echo -e "${GREEN}✅ Successfully seeded ${count} documents!${NC}"
}

# Function to seed bulk data (faster)
seed_bulk() {
    local count=${1:-100}
    echo -e "${YELLOW}🚀 Bulk seeding ${count} documents...${NC}"
    echo ""

    local bulk_data=""

    for i in $(seq 1 $count); do
        bulk_data+='{"index":{"_index":"'${INDEX_NAME}'"}}'$'\n'
        bulk_data+=$(generate_document $i)$'\n'
    done

    curl -s -X POST "${ES_URL}/_bulk" \
        -H 'Content-Type: application/x-ndjson' \
        -d "${bulk_data}" > /dev/null

    echo -e "${GREEN}✅ Bulk seeded ${count} documents!${NC}"
}

# Function to show stats
show_stats() {
    echo -e "\n${BLUE}📊 Index Statistics:${NC}"
    curl -s "${ES_URL}/${INDEX_NAME}/_count" | python3 -m json.tool 2>/dev/null || \
        curl -s "${ES_URL}/${INDEX_NAME}/_count"
}

# Function to clear index
clear_index() {
    echo -e "${YELLOW}🗑️  Clearing all documents from ${INDEX_NAME}...${NC}"
    curl -s -X POST "${ES_URL}/${INDEX_NAME}/_delete_by_query" \
        -H 'Content-Type: application/json' \
        -d '{"query": {"match_all": {}}}' > /dev/null
    echo -e "${GREEN}✅ Index cleared!${NC}"
}

# Main
main() {
    case "${1:-}" in
        --seed)
            seed_documents ${2:-100}
            show_stats
            ;;
        --bulk)
            seed_bulk ${2:-100}
            show_stats
            ;;
        --clear)
            clear_index
            ;;
        --stats)
            show_stats
            ;;
        *)
            echo -e "${CYAN}Usage:${NC}"
            echo "  ./seed-data.sh --seed [count]   Seed documents one by one (default: 100)"
            echo "  ./seed-data.sh --bulk [count]   Bulk seed documents (faster)"
            echo "  ./seed-data.sh --clear          Clear all documents"
            echo "  ./seed-data.sh --stats          Show index statistics"
            echo ""
            echo -e "${CYAN}Environment variables:${NC}"
            echo "  ES_HOST       Elasticsearch host (default: localhost)"
            echo "  ES_PORT       Elasticsearch port (default: 9200)"
            echo "  INDEX_NAME    Index name (default: electric-safai-test)"
            ;;
    esac
}

main "$@"
